on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

name: Project check
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Init Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.18'

    - uses: actions/checkout@master
      name: Checkout

    - name: Install dependencies
      run: |
        npm install

    - name: Run checks
      run: |
        npm test
